


ORANGE_CAR_ID = "45"
ORANGE_CAR_MAC = "00:06:66:61:9B:2D"

PINK_CAR_ID = "10"
PINK_CAR_MAC = "00:06:66:47:0A:0A"

GREEN_CAR_ID = "61"
GREEN_CAR_MAC = "00:06:66:61:A9:3D"

RED_CAR_ID = "72"
RED_CAR_MAC = "00:06:66:61:A3:48"

BLUE_CAR_ID = "5"
BLUE_CAR_MAC = "00:06:66:61:A6:CD"

YELLOW_CAR_ID = "47"
YELLOW_CAR_MAC = "00:06:66:61:9E:F7"

BLACK_CAR_ID = "65"
BLACK_CAR_MAC = "00:06:66:61:9E:A5"



MAC_TO_ID = {ORANGE_CAR_MAC: ORANGE_CAR_ID,
			 PINK_CAR_MAC: PINK_CAR_ID,
			 GREEN_CAR_MAC: GREEN_CAR_ID,
			 RED_CAR_MAC: RED_CAR_ID,
			 BLUE_CAR_MAC: BLUE_CAR_ID,
			 YELLOW_CAR_MAC: YELLOW_CAR_ID,
			 BLACK_CAR_MAC: BLACK_CAR_ID}

ID_TO_MAC = {ORANGE_CAR_ID: ORANGE_CAR_MAC,
			 PINK_CAR_ID: PINK_CAR_MAC,
			 GREEN_CAR_ID: GREEN_CAR_MAC,
			 RED_CAR_ID: RED_CAR_MAC,
			 BLUE_CAR_ID: BLUE_CAR_MAC,
			 YELLOW_CAR_ID: YELLOW_CAR_MAC,
			 BLACK_CAR_ID: BLACK_CAR_MAC}
